name: Keep Database Alive

on:
  schedule:
    - cron: "0 0 */5 * *"  # Runs at midnight every 5th day
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Backend
        run: |
          curl -X GET "https://blog-app-glez.onrender.com/" || echo "Ping failed"
