name: Keep Database Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Backend
        run: |
          curl -X GET "https://blog-app-glez.onrender.com/" || echo "Ping failed"
